### ISSUE TITLE
Custom prefix character is removed from every part of the command

### ISSUE THREAD

**Issue by DBTDerpbox** [ChewMC/CustomCommandPrefix#2]
When typing a command, the custom prefix is being removed from the entire command being sent to the server, for example if I type `.tp .Steve` the server will be sent `/tp Steve` instead of the expected `/tp .Steve`

This can be an issue when floodgate players have the same prefix as the custom command prefix

**Comment by Chew** [comment]
Good catch! I guess I misunderstood Java'a `.replace()`. I'll upload a new build to Spigot whenever I'm able to... 

Feel free to try and let me know if it works :)

https://cdn.chew.pro/jars/CustomCommandPrefix-1.1.jar

**Comment by DBTDerpbox** [comment]
seems to work now, thanks!
